import requests
import json

# ROOT_URL = 'http://localhost:58888'

# response = requests.post(f'{ROOT_URL}/u', json={
#     'userPlatName': '13592547939-qwen2.5-coder:7b',
#     'userNickname': 'QwenHalfFiveCoder',
#     'userRealName': 'qwen2.5-coder:7b',
#     'userLocation': '192.168.0.0',
#     'occupationTitle': 'coderAI',
#     'userProperties': {
#         'age': 3,
#         'gender': 0,
#         'selfDesc': 'I am an evil coder AI',
#         'hobbies': 'answer and ask questions',
#         'workLocation': 'Gee Mac Air Pro',
#         'userId': 1000,
#         'pledgeTag': 'coderAI',
#         'avatar': '',
#         'contactCard': '',
#         'userType': 0
#     }
# })

# response = requests.get(f'{ROOT_URL}/u?username=13592547939-qwen2.5-coder:7b')

# response = requests.post(f'{ROOT_URL}/land', json={
#     'location': 'Manually Added Supposed to be generated by Qwen2.5 coder AI',
#     'tag': '#The Left Pholandgy',
#     'areaMeasured': 'For the golang is not quite there yet',
#     'description': 'Well I have to say that the golang is not quite there yet, I need to put something in there.',
#     'ownerId': 1,
#     'crops': [{
#         'tag': 'freefall',
#         'areaMeasured': '',
#         'description': '',
#         'donationLimit': 0,
#         'plantablilityCategories': 'default'
#     }]
# })

# response = requests.post(f'{ROOT_URL}/land/farms?isPost=true', json={
#     'searchFilterParamDtoList': [],
#     'pageSize': 5,
#     'pageNumber': 0,
#     'extra': None,
#     'sort': 'time',
#     'searchTag': '',
#     'isRandom': 0
# })


# def handle_response(response):
#     if response.status_code == 200:
#         # Check if response is JSON
#         if 'application/json' in response.headers.get('Content-Type', ''):
#             # Parse JSON and pretty-print
#             data = response.json()
#             pretty_json = json.dumps(data, indent=4)
#             print("Response::")
#             print(pretty_json)
#         else:
#             # If not JSON, print raw text
#             print("##-Response is not JSON. Raw content:")
#             print(response.text)
#     else:
#         print(f"###-Request failed with status code: {response.status_code}")
#         print(response.text)


# handle_response(response)


from pytube import YouTube
# YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()
yt = YouTube('https://www.youtube.com/watch?v=5Ixd_I0A4kE&list=PLjOXaNREsD91Jb8vxikMv9KhwqNggYiph&index=10&pp=gAQBiAQB8AUB')
yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download()
